// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMzCOsIhB8Uqnu4_qoefEisey7l4o6LGo',
    appId: '1:448742480488:web:7b8ed41feef9708e2a39dd',
    messagingSenderId: '448742480488',
    projectId: 'book-app-3497d',
    authDomain: 'book-app-3497d.firebaseapp.com',
    storageBucket: 'book-app-3497d.firebasestorage.app',
    measurementId: 'G-TEFYKNRV8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Mf9l3vZp4s5i8SHiM2ig3SHpdlyyHFw',
    appId: '1:448742480488:android:9a0c860890a22aad2a39dd',
    messagingSenderId: '448742480488',
    projectId: 'book-app-3497d',
    storageBucket: 'book-app-3497d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMr-5HltyFmzO5SegamchzvQMYlrcLbJ4',
    appId: '1:448742480488:ios:f7ae2bd87cdfe93f2a39dd',
    messagingSenderId: '448742480488',
    projectId: 'book-app-3497d',
    storageBucket: 'book-app-3497d.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );
}
